# Chapter 3 — Exercise 2: MNIST Data Augmentation


## Exercise

Write a function that can shift an MNIST image in any direction (left, right, up, or down) by one pixel.

Then, for each image in the training set, create four shifted copies (one per direction) and add them to the training set.

Finally, train your best model on this expanded training set and measure its accuracy on the test set. You should observe that your model performs even better now. This technique of artificially growing the training set is called **data augmentation** or **training set expansion**.


## Approach / notes

- Use `scipy.ndimage.shift` (e.g. `shift(image, [2, 1], cval=0)` shifts two pixels down and one right)
- Reshape each flat 784-vector to 28x28 before shifting, then flatten back
- Expanded training set will be 5x the original size (1 original + 4 shifted)
- Re-run the best `KNeighborsClassifier` from Exercise 1 and compare accuracy

_Add your working notes as you go._


## Setup


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(42)


## Solution

_Start writing your solution here._


In [17]:
# Load the MNIST dataset
from sklearn.datasets import fetch_openml
from sklearn.neighbors import KNeighborsClassifier

mnist = fetch_openml('mnist_784', as_frame=False)
x, y = mnist.data, mnist.target
x_train, y_train = x[:60000], y[:60000]
x_test,  y_test  = x[60000:], y[60000:]

# best params already found in notebook 01 
best_model = KNeighborsClassifier(n_neighbors=4, weights='distance')

print(x_train)
print(x_train.shape, y_train.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(60000, 784) (60000,)


In [ ]:
# reshape data
from scipy import ndimage
x_train_aug = []
for row in x_train:
    reshaped_row = row.reshape(28, 28)
    image_1 = ndimage.shift(reshaped_row, [1,0], cval=0)
    image_2 = ndimage.shift(reshaped_row, [0,1], cval=0)
    image_3 = ndimage.shift(reshaped_row, [-1,0], cval=0)
    image_4 = ndimage.shift(reshaped_row, [0,-1], cval=0) 
    x_train_aug.append(reshaped_row.flatten())
    x_train_aug.append(image_1.flatten())
    x_train_aug.append(image_2.flatten())
    x_train_aug.append(image_3.flatten())
    x_train_aug.append(image_4.flatten())
x_train_aug = np.array(x_train_aug)
y_train_aug = []
for row in y_train:
    y_train_aug.append(row)
    y_train_aug.append(row)
    y_train_aug.append(row)
    y_train_aug.append(row)
    y_train_aug.append(row)
y_train_aug = np.array(y_train_aug)
print(x_train_aug.shape, y_train_aug.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (300000,) + inhomogeneous part.